/* Create database */
CREATE DATABASE 'kunst_v1';

USE 'kunst_v1';

CREATE TABLE IF NOT EXISTS 'CUSTOMER' ( 
  ID PRIMARY KEY AUTOINCREMENT INT(10) NOT NULL,
  NAME VARCHAR(50) NOT NULL,
  SURNAME VARCHAR(50) NOT NULL,
  EMAIL VARCHAR(120) NOT NULL,
  PHONE VARCHAR(20) NOT NULL,
  PASSWORD VARCHAR(500) NOT NULL,
  SESSION_KEY VARCHAR(100) NOT NULL,
  BIRTHDAY VARCHAR(20) NOT NULL,
  IS_DOCTOR BOOLEAN NOT NULL /* Si es doctor es true \ Si no es doctor es false */
);

/* USER IS DOCTOR  */
CREATE TABLE IF NOT EXISTS 'PROFILE_DOCTOR' (
  /* Verificamos la fiabilidad del doctor agregado al sistema */

  DOCTOR_LEGACY BOOLEAN NOT NULL
)

CREATE TABLE IF NOT EXISTS 'HORARIOS' (
  ID PRIMARY KEY AUTOINCREMENT INT(10) NOT NULL,
  ID_CUSTOMER_DOCTOR INT(10) NOT NULL,
  MONDAY BOOLEAN NOT NULL,
  ...
  MORNING_TURNING_INIT VARCHAR(20) NOT NULL,
  MORNING_TURNING_FINISHED VARCHAR(20) NOT NULL,
  ...
)

CREATE TABLE IF NOT EXISTS 'CONSULTA' (
  ID PRIMARY KEY AUTOINCREMENT INT|(10) NOT NULL,
  ID_CUSTOMER INT(10) NOT NULL,
  ID_CUSTOMER_DOCTOR INT(10) NOT NULL,
  ARRIVED_TIME VARCHAR(20) NOT NULL, /* 30 - 60 min */
  ARRIVED_DAY VARCHAR(20) NOT NULL,
  PAYMENT VARCHAR(20) NOT NULL
)

CREATE TABLE IF NOT EXISTS 'CONSULTA_RECETA' (
  
)

/* HISTORIAL MEDICO === SELECT * FROM 'CONSULTA' WHERE ID_CUSTOMER= :id_customer 

